# -- Exercise 1: Determination of atomization energy of a small molecule and nanotube molecular dynamics -- #
## 0. Introduction to the course

Welcome to Molecular and Materials Modelling in the Spring Semester 2024 at the ETH
Zürich. This interdisciplinary course will explore many facets of computational physics and
materials science using classical, semi-classical, and quantum-mechanical methodologies.
In this course, we will gain:

- the ability to select a suitable atomistic approach to model a nanoscale system,
and to employ a simulation package to compute quantities, thereby providing a
theoretically-sound explanation of the results of a given experiment;

- knowledge of empirical force fields and insight into electronic structure theory, with
emphasis on density-functional theory

- proficiency in experiments performed in silico. We will interpret the experimental in-
put, choose the level of theory, model the approximations, perform calculations on a
supercomputer, and finally collect and represent the results using Juypter notebooks
and Python scripting.

### 0.1. Course structure

The meeting times and places of this course are as follows:

- Semester: Spring Semester 2024
- Wednesdays: lecture from 8.15 - 10.00;
- Credit points: 6 LP (dt. *Leistungspunkte*)
- Meeting place: ETZ E9 in ETH Zentrum
- Final grade: The final grade will be the result of a 30 minutes individual oral exam
on the course topics (50%) and the cumulative grade about exercises assigned after
each exercise appointment (50%). The students will receive a small computational
exercise about the topics treated in the class, that could be solved within different
programming environments (we provide python based Jupyter notebooks) and if
necessary high performance computing resources. A short report and/or answer to
a few questions will be delivered at the next lecture appointment. At the end of the
oral exam, the solutions will be briefly discussed and a grade will be given which
will take into account the commitment and the quality of the solutions/report, as
well as the discussion on them at the exam.

### 0.2. Course content

The lectures and accompanying exercises will be divided as described in the theory part. 

### 0.3. Assignments structure

Assignments are designed to allow the students to apply the content of the lecture in a
hands-on setting. As such, they constitute an integral aspect of the course – a fact reflected
in their weighting of 50% of the final grade.

**For organizational reasons, after downloading the exercise from the Terminal of the aiidalab environment, copy the exercise-1-workbook.ipynb INTO studentname_exercise-1-workbook.ipynb AND WORK ON THE LATTER FILE. In this way, any further "pull" from the git will not delete your efforts **

Assignments are to be completed within the Jupyter notebook itself, **within the
respective fields in which they appear** in the exercise-i-workbook_studentname.ipynb file. For
answers which are to be written in text (an explanation or elucidation of a phenomenon,
for instance), the cell should be in the markdown format. For answers involving bash
scripting (or really any coding environment), the `<code></code>` environment within the markdown format should suffice.
Standard Python code can be written directly in the cell. All assignments, which are to
be submitted for grading, will appear in a box such as this:

#### Assignment 1: Playing with Markdown and Latex

In this course, we will be making ample use of both Markdown and Python within a Jupyter Notebook. In order to familiarise ourselves with some of the syntax, here are some introductory tasks to practice different modes of syntax:
1. Sometimes we will want to highlight words or phrases by means of bold or italicised text. Write something in bold, something in italicised, and then something in bold and italicised text.
2. Formatting and appearance are important. Typeset "import matplotlib.pyplot as plt" here in Markdown using the monospaced slab serif typeface, so that it 'looks' more like code.
3. Write the time-dependent 3D Schrödinger Equation (so, using the del-operator) in SI-units (so, with all the physical constants) for some arbitrary wavefunction $\psi(\vec{x})$ and some arbitrary potential $V(x)$ for $x := |\vec{x}|$. If you don't know the Schrödinger Equation by heart, just Google it.

#### End Assignment 1

..., and should furthermore fulfill **all** of the following criteria:

- Assignments shall be submitted **on or before 18.00h of the following Sunday**
to `daniele.passerone@empa.ch` giving the link to a polybox or a git **folder** with the submission;
- Assignments should be submitted as **folders** containing all necessary files to ensure their proper opening, including but not limited to generated image and text files. *Please do not include the wavefunction `.wfn` files in the submitted folder, as these files are quite large*.
- The Jupyter notebooks themselves should follow the format: studentname_exercise-i-workbook.ipynb, where i of
course denotes the exercise / week number;
- Assignments should be sensibly worked out, even if the submitted solution is incor-
rect. **If, after having attempted the solution, and after Googling around
for help, you are still unable to arrive at a working answer, please explain
what you tried and what you searched for in your submission**, and, if
necessary, what logic you applied and where you got stuck. Standstills are
all too common in original research, for which reason you will still get credit for
the exercise for a reasonably thorough explanation.

If all of this seems a bit overwhelming, don’t worry – we’ll cover everything in this
course, and Daniele Passerone, and Carlo Pignedoli are of course
reachable by email. Solutions will then be posted by the following Monday.

### 0.3. The *compendium scriptorum*

Over the course of the semester, we will be using several bash scripts to automate certain
tasks or extract data. Scripts which are to be added to this compendium scriptorum will
be enclosed in the following box:

```
#!/bin/bash
##--SCRIPT TO BE ADDED--##
```

## 1 The Atomic Simulation Environment

### 1.2 The atomization energy of a acetylene molecule

We begin toying around with the Atomic Simulation Environment (ASE) by investigating
some basic properties of materials: in the current exercise, we first want to use ASE to
calculate the **atomization energy** of a nitrogen molecule. The atomization energy,
or more precisely, the **enthalpy of atomization**, is defined as the change in enthalpy
$∆_{at}H$ when the bonds of a compound are broken, and the component atoms are thereby
separated into individual atoms. We therefore arrive at the following definition: $$∆_{at}H=-(E_{N_2} - 2E_N), $$
where $E_{N_2}$ and $E_N$ represent the energy of the $N_2$ molecule and that of the single N atom, respectively. 
We will apply the same concept to a polyatomic molecule.

#### Assignment 2: Atomization energy
Why must the atomization energy always be positive?
<br> A:

In [1]:
from ase import Atoms
from ase.optimize import BFGS
from ase.calculators.emt import EMT
import nglview as nv
import numpy as np

Atoms objects containing the atoms are created and a fast EMT – effective
medium theory – calculator is attached to it simply as an argument. In ASE, a calculator
is a sort of ”black box” which can take atomic numbers and atomic positions from an Atoms
object and calculate the energy, forces, and (sometimes) stresses. In order to calculate
forrces and energies, we need to attach a calculator to an Atoms object. The total energy
for the isolated atoms is then calculated and stored in the e_atom variable.
In the following cell we define the atom species as well as the atomic coordinates of
the acetylene molecule,

In [2]:
atom = Atoms('C')
atom.calc = EMT()
e_atom_c = atom.get_potential_energy()
atom = Atoms('H')
atom.calc = EMT()
e_atom_h = atom.get_potential_energy()

In the following cell we define the atom species as well as the atomic coordinates of
the acetylene molecule, **optimize the molecule** using the BFGS algorithm and then calculate the atomization energy according to the equation above:

In [15]:
d = 1.203
dh = 1.06
molecule = Atoms('HCCH', [(0., 0., -dh), (0., 0., 0.), (0., 0., d), (0., 0., d+dh)])
molecule.calc = EMT()
e_molecule_0 = molecule.get_potential_energy()
molecule_0 = molecule
print ("\nPositions at the beginning\n")
print (molecule.get_positions())
print ("\n Doing potential optimization\n")
dyn = BFGS(molecule)
dyn.run(fmax=0.05)

print ("\nPositions at the end\n")
print (np.round(molecule.get_positions(),decimals = 5))
e_molecule = molecule.get_potential_energy()

print ("initial, final energy ",e_molecule_0,e_molecule)
view_structure(molecule_0)




Positions at the beginning

[[ 0.     0.    -1.06 ]
 [ 0.     0.     0.   ]
 [ 0.     0.     1.203]
 [ 0.     0.     2.263]]

 Doing potential optimization

      Step     Time          Energy         fmax
BFGS:    0 23:25:18        1.741414        5.9894
BFGS:    1 23:25:18        0.977453        0.9330
BFGS:    2 23:25:18        0.962058        0.2159
BFGS:    3 23:25:18        0.960718        0.1845
BFGS:    4 23:25:18        0.958395        0.0194

Positions at the end

[[ 0.      -0.      -1.09691]
 [-0.      -0.       0.10675]
 [ 0.       0.       1.09625]
 [ 0.      -0.       2.29991]]
initial, final energy  1.74141387912011 0.9583950776390268


NGLWidget()

We can view the structure:

In [4]:
def view_structure(structure):
    """
    Use the ASE library to view an atoms object.

    Parameters
    ----------

    structure: Atoms object

    Returns
    -------

    NGLWidget with GUI: object to be viewed
    
    """
    #t1=make_supercell(structure,[[3,0,0],[0,3,0],[0,0,3]])
    t = nv.ASEStructure(structure)
    w = nv.NGLWidget(t, gui=True)
    w.add_unitcell()
    w.add_spacefill()
    return w

def view_trajectory(trajectory):
    t2 = nv.ASETrajectory(trajectory)
    w2 = nv.NGLWidget(t2, gui=True)
    #w2.add_unitcell()
    w2.add_spacefill()
    return w2

In [5]:
view_structure(molecule)

NGLWidget()

and then calculate the atomization energy according to Eq. 1.2:

In [6]:
e_atomization = e_molecule - 2 * e_atom_c - 2*e_atom_h

Running the last cell in this section generates the output we want:

In [7]:
print('Carbon atom energy: %5.2f eV' % e_atom_c)
print('Hydrogen atom energy: %5.2f eV' % e_atom_h)
print('C2H2 molecule energy: %5.2f eV' % e_molecule)
print('Atomization energy: %5.2f eV' % -e_atomization)


Carbon atom energy:  3.50 eV
Hydrogen atom energy:  3.21 eV
C2H2 molecule energy:  0.96 eV
Atomization energy: 12.46 eV


## 2 LAMMPS: carbon nanotube molecular dynamics

### 2.1 Running lammps

We go to the folder Exercise_1, and we observe the file 
<code>inputC.lammps</code>. This is the input file for the molecular dynamics code lammps, that allows running several kinds of computer experiments. A MD run to heat a carbon nanotube will be tested. A thermostat (see a next lecture) will be used to gradually increase the temperature of the system to 1000 K. The potential used is of the family of the Tersoff potential (bond order), suitable for allotropes of carbon. 
The input structure can be inspected with the internal viewer or the viewer **vmd** (to be installed on the local machine). 



In [8]:

from ase import Atom,Atoms
from ase.io import read, lammpsdata
from ase.visualize import view

import matplotlib.pyplot as plt


data_cnt = read ("cnt_C.data",format="lammps-data",style="molecular")


nat = len(data_cnt)
carbons = np.empty(nat); carbons.fill(6)
data_cnt.set_atomic_numbers(carbons) #transforming into carbons for the visualization

print (data_cnt.get_distance(1,2)) #check first neighbor distance
view_structure(data_cnt)




1.4183065739948464


NGLWidget()

We run the simulation giving the command (in the terminal)
<code>lmp_serial -in inputC.lammps</code>

We can now load the resulting trajectory and observe it here. 

In [9]:
traj_cnt = read("dumpC.lammpstrj",":")

print (type(data_cnt))

for atoms in traj_cnt:
    atoms.set_atomic_numbers(carbons)
    #print (atoms.get_distance(2,3))


view_trajectory(traj_cnt)


<class 'ase.atoms.Atoms'>


NGLWidget(max_frame=300)



#### Assignment 2: Observations
What do you observe by looking at the trajectory?

### 2.1 Running a copper nanotube

We now look at the file <code>cnt_cu.data</code> that will be read by the file <code>inputCu.lammps</code> using this time the embedded atom model for metals. The coordinates of the nanotube have been rescaled to have a bond distance suitable to Cu.



In [13]:
data_cnt = read ("cnt_cu.data",format="lammps-data",style="molecular")


nat = len(data_cnt)
copper = np.empty(nat); copper.fill(29)
data_cnt.set_atomic_numbers(copper) #transforming into copper for the visualization
print (data_cnt.get_distance(1,2)) #check first neighbor distance
view_structure(data_cnt)



2.532735408012453


NGLWidget()

Now we run lammps again, for heating (much less than before) the system (see in the input file)

<code>lmp_serial -in inputCu.lammps</code>.
We visualize again:


In [14]:
traj_cnt = read("dumpCu.lammpstrj",":")

print (type(data_cnt))

for atoms in traj_cnt:
    atoms.set_atomic_numbers(copper)
    #print (atoms.get_distance(2,3))


view_trajectory(traj_cnt)


<class 'ase.atoms.Atoms'>


NGLWidget(max_frame=300)



#### Assignment 3: Observations
What do you observe by looking at the trajectory this time?